language: ruby
rvm:
- 2.2.0
sudo: false
cache: bundler
git:
  submodules: false
script: bundle exec jekyll b --trace
notifications:
  email:
    recipients:
    - eric.mill@gsa.gov
    on_success: change
    on_failure: change
branches:
  only:
  - master
deploy:
  edge: true
  provider: cloudfoundry
  username: e1cf88e3-77f0-45d5-aa66-7df30dcafdaa
  password:
    secure: j9yh2kYGAQ/bnEirwL6/Uzw+TTu5MxuMVdJBQFbBYjjNZw7o0X8ik2PNXjpWK8CS6nOiDCK0VA/o7qdoqvVb5uYXqe9s3TThFt5iCA5nFgl9Re7eXUZ+S/bSFcP8dGxb5opw7xp+IygBxhWJ6w1CiacEO4E40FtUTFl88SiFp3U=
  api: https://api.fr.cloud.gov
  organization: gsa-ogp-pulse
  space: https
