language: ruby
rvm:
- 2.2.0
sudo: false
cache: bundler
git:
  submodules: false
script: bundle exec jekyll b --trace
notifications:
  email:
    recipients:
    - eric.mill@gsa.gov
    on_success: change
    on_failure: change
branches:
  only:
  - master
deploy:
  edge: true
  provider: cloudfoundry
  username: 6221ed44-ec90-4757-acda-5f42b63a4945
  password:
    secure: Nnw3KaMVlXGnvfXv/4OkFA45v4NPLqWrLCr7Ivgx5KGl1gdcG5a1s0MPb/DNmDblxArqI8+P5B23IGtTqCURYwzyX1t5mU7bNL1m0PaQ9PolABEavgIyEDD69UUiRWzozEvW9tyt4WN1ksMiAC2Dnue+Nifr0N5Ai3rW9N8Yy1o=
  api: https://api.fr.cloud.gov
  organization: gsa-ogp-pulse
  space: https
